(() => {
  if(globalThis.GemSpiderUI)return;
  const svg=`<svg viewBox="0 0 120 110" aria-hidden="true"><g class="legs" fill="none" stroke="#bcf77b" stroke-width="3" stroke-linecap="round"><path d="M47 52 27 30 12 38"/><path d="M46 58 22 49 6 60"/><path d="M46 65 22 76 8 91"/><path d="M49 70 35 93 25 104"/><path d="M73 52 93 30 108 38"/><path d="M74 58 98 49 114 60"/><path d="M74 65 98 76 112 91"/><path d="M71 70 85 93 95 104"/></g><ellipse cx="60" cy="43" rx="23" ry="30" fill="#202c1b" stroke="#bcf77b" stroke-width="2"/><path d="m60 20 9 13-9 15-9-15Z" fill="#bcf77b"/><ellipse cx="60" cy="65" rx="19" ry="17" fill="#151d12" stroke="#bcf77b" stroke-width="2"/><circle cx="53" cy="65" r="5" fill="#eaffd8"/><circle cx="67" cy="65" r="5" fill="#eaffd8"/><circle cx="54" cy="66" r="2" fill="#182210"/><circle cx="68" cy="66" r="2" fill="#182210"/><path d="m53 81-4 7m18-7 4 7" stroke="#bcf77b" stroke-width="2"/></svg>`;
  class Spider {
    constructor({onPause=()=>{},onClose=()=>{}}={}) {
      this.host=document.createElement('div');this.host.id='gem-search-spider';
      const root=this.host.attachShadow({mode:'closed'});
      root.innerHTML=`<style>:host{all:initial!important;position:fixed!important;inset:0!important;z-index:2147483646!important;pointer-events:none!important;font-family:system-ui,sans-serif!important}.pet{position:fixed;left:0;top:0;width:92px;height:88px;filter:drop-shadow(0 6px 16px #0009);will-change:transform}.pet svg{width:100%;height:100%;overflow:visible}.legs path{transform-origin:60px 60px}.walking .legs path:nth-child(odd){animation:step .22s alternate infinite}.walking .legs path:nth-child(even){animation:step .22s alternate-reverse infinite}@keyframes step{to{transform:rotate(9deg)}}.bubble{position:absolute;bottom:87px;left:0;max-width:210px;width:max-content;background:#172014;color:#d8e9cc;border:1px solid #536c3e;padding:7px 11px;border-radius:10px 10px 10px 0;font-size:10px;box-shadow:0 4px 20px #0005}.dock{position:fixed;right:22px;bottom:22px;width:258px;padding:17px;background:#121a10f5;border:1px solid #526d3b;color:#e9f6df;border-radius:15px;box-shadow:0 12px 40px #0006;pointer-events:auto;backdrop-filter:blur(12px)}.brand{display:flex;align-items:center;gap:8px;font-size:13px;font-weight:650}.dot{height:7px;width:7px;background:#baf577;border-radius:50%;box-shadow:0 0 12px #baf57770}.brand small{margin-left:auto;font-size:8px;letter-spacing:1px;color:#a5b897}.status{font-size:11px;line-height:1.5;color:#a3b599;margin:10px 0;min-height:32px}.numbers{display:flex;gap:20px;margin:12px 0}.numbers b{font-size:23px;font-weight:500}.numbers span{display:block;font-size:9px;color:#94a786;margin-top:2px}.controls{display:flex;gap:7px}.controls button{font:11px system-ui;cursor:pointer;border:1px solid #3c5130;border-radius:6px;background:#23351a;color:#c5e9a9;padding:7px 9px}.controls .close{margin-left:auto;background:none}.focus{position:fixed;box-sizing:border-box;border:1px solid #bbf774;border-radius:13px;box-shadow:0 0 0 3px #b9ff6812;opacity:0;transition:opacity .2s;pointer-events:none}@media(prefers-reduced-motion:reduce){.legs path{animation:none!important}.pet{will-change:auto}}</style><div class="focus"></div><div class="pet">${svg}<div class="bubble">Ready to explore</div></div><div class="dock"><div class="brand"><i class="dot"></i> gem search <small>LOCAL SPIDER</small></div><div class="status">Reading the posts you can see.</div><div class="numbers"><div><b class="read">0</b><span>POSTS OBSERVED</span></div><div><b class="leads">0</b><span>RESEARCH LEADS</span></div></div><div class="controls"><button class="pause">Pause</button><button class="dashboard">Dashboard ↗</button><button class="close" aria-label="Dismiss spider">✕</button></div></div>`;
      document.documentElement.append(this.host);this.pet=root.querySelector('.pet');this.focus=root.querySelector('.focus');this.bubble=root.querySelector('.bubble');this.status=root.querySelector('.status');this.read=root.querySelector('.read');this.leads=root.querySelector('.leads');this.pause=root.querySelector('.pause');
      this.x=Math.max(0,innerWidth-170);this.y=Math.max(0,innerHeight-340);this.target={x:this.x,y:this.y};this.render();
      this.pause.onclick=onPause;root.querySelector('.close').onclick=onClose;root.querySelector('.dashboard').onclick=()=>window.open('http://127.0.0.1:8787','_blank','noopener');
      this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
    }
    render(){this.pet.style.transform=`translate(${this.x}px,${this.y}px)`;}
    go(rect,text='Following a signal…'){
      this.bubble.textContent=text;this.target={x:Math.max(3,Math.min(innerWidth-100,rect.left-88)),y:Math.max(100,Math.min(innerHeight-110,rect.top+rect.height/2-45))};
      Object.assign(this.focus.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px',opacity:'1'});
      cancelAnimationFrame(this.frame);this.pet.classList.add('walking');let last=performance.now();
      const walk=now=>{const delta=Math.min((now-last)/1000,.05);last=now;const dx=this.target.x-this.x,dy=this.target.y-this.y,d=Math.hypot(dx,dy);if(d<2||this.reduced){this.x=this.target.x;this.y=this.target.y;this.render();this.pet.classList.remove('walking');return;}const step=Math.min(d,delta*240);this.x+=dx/d*step;this.y+=dy/d*step;this.render();this.frame=requestAnimationFrame(walk);};this.frame=requestAnimationFrame(walk);
      clearTimeout(this.hideFocus);this.hideFocus=setTimeout(()=>this.focus.style.opacity='0',2000);
    }
    update({read,leads,status,paused,stopped}){if(read!==undefined)this.read.textContent=read;if(leads!==undefined)this.leads.textContent=leads;if(status)this.status.textContent=status;if(paused!==undefined){this.pause.textContent=paused?'Resume':'Pause';this.bubble.textContent=paused?'Taking a little break':'Hunting for signals';if(paused){cancelAnimationFrame(this.frame);this.pet.classList.remove('walking');this.focus.style.opacity='0';}}if(stopped!==undefined){this.pause.disabled=stopped;this.pause.textContent=stopped?'Stopped':'Stop';}}
    destroy(){cancelAnimationFrame(this.frame);clearTimeout(this.hideFocus);this.host.remove();}
  }
  globalThis.GemSpiderUI=Spider;
})();
