from PySide6.QtCore import Qt
from PySide6.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QDialog, QGridLayout, QApplication, QSizePolicy


class TokenDetailsDialog(QDialog):
    def __init__(self, row, metrics, explanation, watch, explorer, parent=None):
        super().__init__(parent)
        self.setWindowTitle('Token details')
        self.resize(620, 440)
        box = QVBoxLayout(self)
        box.setContentsMargins(28, 28, 28, 28)
        box.setSpacing(20)
        title = QLabel(row['name'] if row['name'] != row['address'] else 'Token')
        title.setObjectName('tokenTitle')
        box.addWidget(title)
        address = QLabel(row['chain'].upper() + '\n' + row['address'])
        address.setObjectName('muted')
        address.setWordWrap(True)
        address.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        box.addWidget(address)
        grid = QGridLayout()
        grid.setSpacing(16)
        for index, (name, value) in enumerate(metrics):
            cell = QWidget()
            layout = QVBoxLayout(cell)
            label = QLabel(name)
            label.setObjectName('muted')
            layout.addWidget(label)
            amount = QLabel(value)
            amount.setObjectName('metricValue')
            layout.addWidget(amount)
            grid.addWidget(cell, index // 3, index % 3)
        box.addLayout(grid)
        note = QLabel(explanation)
        note.setObjectName('muted')
        note.setWordWrap(True)
        box.addWidget(note)
        technical = QPushButton('Verification details')
        verification = QLabel(row.get('verification_status', 'Not verified') + '\nMarket values are reported values. The blockchain account check does not verify USD valuation.')
        verification.setWordWrap(True)
        verification.hide()
        technical.clicked.connect(lambda: verification.setVisible(not verification.isVisible()))
        box.addWidget(technical)
        box.addWidget(verification)
        actions = QHBoxLayout()
        follow = QPushButton('Watch token')
        follow.setObjectName('primary')
        follow.clicked.connect(watch)
        actions.addWidget(follow)
        copy = QPushButton('Copy address')
        copy.clicked.connect(lambda: QApplication.clipboard().setText(row['address']))
        actions.addWidget(copy)
        open_button = QPushButton('Explorer')
        open_button.clicked.connect(explorer)
        actions.addWidget(open_button)
        box.addLayout(actions)


class TokenSearchCard(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName('searchCard')
        self.setAttribute(Qt.WidgetAttribute.WA_StyledBackground, True)
        self.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Maximum)
        box = QVBoxLayout(self)
        box.setContentsMargins(24, 20, 24, 20)
        box.setSpacing(12)
        row = QHBoxLayout()
        identity = QVBoxLayout()
        self.title = QLabel('Searching...')
        self.title.setObjectName('tokenTitle')
        identity.addWidget(self.title)
        self.address = QLabel()
        self.address.setObjectName('muted')
        identity.addWidget(self.address)
        row.addLayout(identity, 1)
        self.market = QLabel()
        self.market.setAlignment(Qt.AlignmentFlag.AlignRight)
        self.market.setObjectName('metricValue')
        row.addWidget(self.market)
        box.addLayout(row)
        self.status = QLabel()
        self.status.setWordWrap(True)
        self.status.setObjectName('muted')
        box.addWidget(self.status)
        self.choices = None
        self.actions = QHBoxLayout()
        box.addLayout(self.actions)
